version: '3'

services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    stop_signal: SIGINT
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    ports:
      - 3000:3000
    restart: on-failure

volumes:
  app_bundle:
